---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld-php
  labels:
    app.kubernetes.io/name: helloworld-php
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-php
  labels:
    app.kubernetes.io/name: helloworld-php
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: helloworld-php
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-php
  labels:
    app.kubernetes.io/name: helloworld-php
data:
  nginx.conf: |-
    worker_processes  auto;
    pid /tmp/nginx.pid;
    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] ""$request"" '
                          '$status $body_bytes_sent ""$http_referer"" '
                          '""$http_user_agent"" ""$http_x_forwarded_for""';

        log_format json '{'
                          '"time":"$time_iso8601",'
                          '"remoteIP":"$remote_addr",'
                          '"port":"$server_port",'
                          '"serverIP":"$server_addr",'
                          '"serverName":"$server_name",'
                          '"httpHost":"$hostname",'
                          '"reqTime":"$request_time",'
                          '"resStatus":"$status",'
                          '"protocol":"$http_x_forwarded_proto",'
                          '"sendBytesWithoutHeader":"$body_bytes_sent",'
                          '"sendBytesWithHeader":"$bytes_sent",'
                          '"fpath":"$request_filename",'
                          '"reqURL":"$request_uri",'
                          '"query":"$query_string",'
                          '"headerLocation":"sent_http_location",'
                          '"method":"$request_method",'
                          '"ua":"$http_user_agent",'
                          '"xForwardedFor":"$http_x_forwarded_for",'
                          '"referer":"$http_referer"'
                          '}';

        sendfile        on;
        server_tokens    off;
        keepalive_timeout  61;

        server {
            listen 8080;

            access_log /dev/stdout json;
            error_log /dev/stderr;

            charset UTF-8;
            client_max_body_size 16m;

            #--------------------
            # GZIP settings
            #--------------------
            gzip              on;
            gzip_disable      "msie6"
            gzip_vary         on;
            gzip_proxied      any;
            gzip_comp_level   5;
            gzip_buffers      16 8k;
            gzip_http_version 1.1;
            gzip_types        text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

            root /var/app/public;

            location / {
              index     index.php index.html index.htm;
              try_files $uri /index.php?$query_string;
            }

            location ~ \.php$ {
              fastcgi_pass localhost:9000;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include       fastcgi_params;
              fastcgi_intercept_errors        on;
              fastcgi_ignore_client_abort     off;
              fastcgi_connect_timeout 60;
              fastcgi_send_timeout 180;
              fastcgi_read_timeout 180;
              fastcgi_buffer_size 128k;
              fastcgi_buffers 4 256k;
              fastcgi_busy_buffers_size 256k;
              fastcgi_temp_file_write_size 256k;
            }

            # deny access to .htaccess files, if Apache's document root
            # concurs with nginx's one
            #
            location ~ /\.ht {
                deny  all;
            }

            #--------------------------------------
            # deny .git or .htaccess or .svn files
            #--------------------------------------
            location ~ /\.(ht|git|svn) {
                deny all;
            }

            #--------------------------------------
            # dont save access log for favicon
            #--------------------------------------
            location = /favicon.ico {
                access_log off;
                log_not_found off;
            }

            #--------------------------------------
            # dont save access log for robots.txt
            #--------------------------------------
            location = /robots.txt {
                access_log off;
                log_not_found off;
            }
        }

        server {
            listen 8081;
            access_log /dev/stdout json;
            error_log /dev/stderr;

            location /nginx_status {
              stub_status on;
              access_log off;
            }

            location /phpfpm_status {
              include fastcgi_params;
              fastcgi_pass localhost:9000;
              fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
              access_log off;
            }

            location /phpfpm_ping {
              include fastcgi_params;
              fastcgi_pass localhost:9000;
              fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
              access_log off;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-php
  labels:
    app.kubernetes.io/name: helloworld-php
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-php
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-php
    spec:
      serviceAccountName: helloworld-php
      terminationGracePeriodSeconds: 10
      containers:
        - name: helloworld-php
          image: "hatsunemiku/helloworld-php:latest"
          imagePullPolicy: Always
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: fastcgi
          readinessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: fastcgi
        - name: helloworld-php-nginx
          image: "nginxinc/nginx-unprivileged:1.16"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: status
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
              name: nginx-conf
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /nginx_status
              port: status
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /nginx_status
              port: status
      volumes:
        - name: nginx-conf
          configMap:
            name: helloworld-php
            items:
              - key: nginx.conf
                path: nginx.conf
