---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld-php
  labels:
    app.kubernetes.io/name: helloworld-php
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-php
  labels:
    app.kubernetes.io/name: helloworld-php
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: helloworld-php

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-php
  labels:
    app.kubernetes.io/name: helloworld-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-php
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-php
    spec:
      serviceAccountName: helloworld-php
      containers:
        - name: helloworld-php
          image: "hatsunemiku/helloworld-php:php-latest"
          imagePullPolicy: Always
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: fastcgi
          readinessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: fastcgi
        - name: helloworld-php-nginx
          image: "hatsunemiku/helloworld-php:nginx-latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /nginx_status
              port: http
              httpHeaders:
                - name: X-Probe-Header
                  value: "3939"
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /nginx_status
              port: http
              httpHeaders:
                - name: X-Probe-Header
                  value: "3939"
